spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    servlet:
      multipart:
        enabled: true
        location: C:\update
        max-request-size: 30MB
        max-file-size: 30MB
security:
  jwt:
    secret: secret-value
shop:
  upload:
    path: C:\update

UserController:
  signup: Creates user and returns its JWT token
  signin: Authenticates user and returns its JWT token
